export const GLOSSARY: { term: string; definition: string }[] = [
  { term: 'Quoted rate', definition: 'The headline interest rate the lender tells you, e.g. “10.99% p.a.” It may be flat or reducing.' },
  { term: 'Reducing balance', definition: 'Interest charged on the outstanding principal, which falls as you repay.' },
  { term: 'Flat rate', definition: 'Interest charged on the original loan amount for the whole tenure. Costs much more than the same reducing rate.' },
  { term: 'APR (Annual Percentage Rate)', definition: 'RBI: the annual cost of credit to the borrower, including interest and all other charges. Shown in the KFS.' },
  { term: 'Estimated effective annualized cost', definition: 'Our calculation: the IRR of the cash flows you enter (money received, EMIs, charges), annualized like RBI’s KFS illustration. An estimate, not the lender’s official APR.' },
  { term: 'Compounded effective annual rate', definition: 'The same cash-flow rate with monthly compounding: (1 + monthly rate)^12 − 1. Always a bit higher than the ×12 figure.' },
  { term: 'KFS (Key Facts Statement)', definition: 'A standard summary of a loan’s key terms, APR, charges and repayment schedule.' },
  { term: 'Net disbursed amount', definition: 'Loan amount minus upfront charges — the money you actually receive.' },
  { term: 'EMI', definition: 'Equated monthly instalment: a fixed monthly payment covering interest and principal.' },
  { term: 'Amortization', definition: 'How each EMI is split between interest and principal over the life of the loan.' },
  { term: 'Tenure', definition: 'The length of the loan, in months or years.' },
  { term: 'Part-prepayment', definition: 'Paying part of the principal early to reduce future interest.' },
  { term: 'Foreclosure', definition: 'Paying off the entire loan before the tenure ends.' },
  { term: 'Balance transfer', definition: 'Moving an outstanding loan to another lender, usually for a lower rate.' },
  { term: 'Benchmark', definition: 'The reference rate a floating loan is linked to (e.g. repo rate, T-bill, MCLR).' },
  { term: 'Spread', definition: 'The margin added to the benchmark to get your floating rate.' },
  { term: 'Penal charge', definition: 'A charge for not meeting a loan condition. It must not be penal interest and cannot attract further interest.' },
  { term: 'Pre-EMI', definition: 'Interest-only payments on a partly disbursed loan (e.g. under-construction homes).' },
  { term: 'Broken-period interest', definition: 'Interest for the odd days between disbursement and the first full EMI period.' },
  { term: 'Advance EMI', definition: 'EMIs collected at disbursement instead of at the end of the first month.' },
  { term: 'Loan Deal Score', definition: 'This app’s 0–100 score of a loan’s cost and transparency, based only on what you enter. Not a credit score, not CIBIL, not a lender rating.' },
  { term: 'Data confidence', definition: 'How reliable a result is, based on whether your numbers came from documents or estimates.' },
  { term: 'LSP', definition: 'Lending Service Provider: an app or agent that sources loans for a regulated lender.' },
  { term: 'NBFC', definition: 'Non-Banking Financial Company, regulated by RBI. HFCs (housing finance companies) are a type of NBFC.' },
]
